# Define common environment variables at the top level
x-qdrant-env: &qdrant-env
  QDRANT_HOST: qdrant
  QDRANT_PORT: 6333
  QDRANT_COLLECTION: test-collection

services:
  # for development purposes
  dev:
    build:
      context: ../../
      dockerfile: components/wr-qdrant-embeddings/Dockerfile
    volumes:
      - ./component_config:/code/component_config
      - ./data:/data
      - ../_common/src:/code/src
    command: [ "python", "-u", "/code/src/component.py" ]

  # Qdrant database for testing
  qdrant:
    build:
      context: ./tests/mocks/qdrant
    environment:
      <<: *qdrant-env
    ports:
      - "6333:6333"

  # Mock OpenAI API service for testing embeddings
  openai-mock:
    build:
      context: ./_common/tests/mocks/openai-mock
    ports:
      - "8001:8000"

  test:
    # Use to run flake8 and unittests checks
    build:
      context: ../../
      dockerfile: components/wr-qdrant-embeddings/Dockerfile
    depends_on:
      qdrant:
        condition: service_started
      openai-mock:
        condition: service_healthy
    volumes:
      - ./component_config:/code/component_config
      - ./data:/data
      - ../_common/src:/code/src
      - ./scripts:/code/scripts
      - ./tests:/code/tests
    environment:
      <<: *qdrant-env
      OPENAI_API_KEY: sk-fake-key-for-testing
      OPENAI_MODEL: text-embedding-3-small
      OPENAI_API_BASE: http://openai-mock:8000
      QDRANT_HOST: http://qdrant:6333
    command:
      - /bin/sh
      - -c
      - |
        set -e
        cd /code/
        /code/.venv/bin/python -m unittest discover