name: 'Check Version Change'
description: 'Checks if component Version file has changed between commits'

inputs:
  component:
    description: 'Component name to check'
    required: true

outputs:
  has_version_change:
    description: 'Whether the Version file has changed'
    value: ${{ steps.check.outputs.has_version_change }}
  version:
    description: 'Current version from Version file'
    value: ${{ steps.check.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: |
          ${{ inputs.component }}/VERSION

    - name: Check version change
      id: check
      shell: bash
      run: |
        version_file="${{ inputs.component }}/VERSION"
        
        # Debug výstup
        echo "Checking version file: $version_file"
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
        
        # Check if Version file exists
        if [ ! -f "$version_file" ]; then
          echo "Version file not found at $version_file"
          echo "has_version_change=false" >> $GITHUB_OUTPUT
          echo "version=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Get current version
        current_version=$(cat "$version_file")
        echo "Current version: $current_version"
        echo "version=$current_version" >> $GITHUB_OUTPUT
        
        # If we're on a tag, always consider it a version change
        if [[ "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "On version tag - marking as version change"
          echo "has_version_change=true" >> $GITHUB_OUTPUT
        # Otherwise check if VERSION file changed
        elif [[ "${{ steps.changed-files.outputs.all_changed_files }}" == *"$version_file"* ]]; then
          echo "VERSION file changed"
          echo "has_version_change=true" >> $GITHUB_OUTPUT
        else
          echo "No version change detected"
          echo "has_version_change=false" >> $GITHUB_OUTPUT
        fi 