# This workflow is used to build and deploy the app-embeddings-v2 component
name: app-embeddings-v2

on:
  push:
    paths:
      - 'components/app-embeddings-v2/**'
      - 'components/_common/**'
      - '.github/workflows/**'

jobs:
  ci:
    uses: ./.github/workflows/templates/component-workflow.yml
    with:
      component_dir: ./components/app-embeddings-v2
      kbc_developerportal_app: keboola.app-embeddings-v2
      kbc_developerportal_vendor: keboola
      kbc_test_project_configs: ""
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ vars.KBC_DEVELOPERPORTAL_USERNAME }}
      KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
      KBC_STORAGE_TOKEN: ${{ secrets.KBC_STORAGE_TOKEN }} 